---
# MegaLinter configuration file
# https://megalinter.github.io/configuration/

# Enable only YAML and JSON linters
enable:
  - JSON
  - YAML

disable_all: true

# Exclude patterns
filter_regex_exclude:
  - '.*(\.github)/.*'
  - '.*\.md$'

# Don't treat warnings as errors
warnings_as_errors: false

# Logging
log_level: NOTICE
