---
name: Lint Code Base

on:
  push:
    branches-ignore:
      - "main"
      - "master"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  mega-linter:
    name: MegaLinter
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEGALINTER_CONFIG: .megalinter.yml
          PARALLEL: false
          WARNINGS_AS_ERRORS: false
          LOG_LEVEL: ERROR
